### ISSUE TITLE
About homework solutions

### ISSUE THREAD

**Issue by chibohe** [mryab/efficient-dl-systems#13]
So much thanks for such a great course.I have been taking this course for about a month, and I currently get stuck in week 06, can you provide me a solution about week 06 homework. Looking forward to your reply, thanks.

**Comment by mryab** [comment]
Hi @chibohe! Unfortunately, we cannot publish solutions to the homework, as the same assignment will likely be given in future years (in one form or another), and we want to ensure that students come up with original solutions. Moreover, the majority of assignments in our course have a substantial creative component, so it is not possible to provide a "default" solution.
