### ISSUE TITLE
HW3: Requirements and typing update

### ISSUE THREAD

**Issue by VladPyzh** [mryab/efficient-dl-systems#15]
During creating enviroment from requirements.txt for the 3rd week assigment the conflict occurs: 

`The conflict is caused by:
    The user requested torch==2.2.0
    torchvision 0.16.2 depends on torch==2.1.2`

Possible solution: `0.16.2` -> `0.17.0`

Also in train.py typings have changed. Now error appears:
`AttributeError: module 'torch.optim' has no attribute 'optimizer'. Did you mean: 'Optimizer'?`
`AttributeError: module 'torch.nn.modules' has no attribute '_Loss'. Did you mean: 'loss'?`

**Comment by mryab** [comment]
Resolved by https://github.com/mryab/efficient-dl-systems/pull/16
